name: Converted Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - run: >-
          composer require --no-update --dev roots/wordpress:${WP_VERSION}
          wp-phpunit/wp-phpunit:${WP_VERSION}
      - run: '[ $TRAVIS_PHP_VERSION == ''8.0'' ] || composer install'
      - run: >-
          [ $TRAVIS_PHP_VERSION != '8.0' ] || composer install
          --ignore-platform-reqs
      - run: composer show
      - run: >-
          mysql -u root -e "GRANT ALL PRIVILEGES ON ${WP_DB_NAME}.* TO
          ${WP_DB_USER} IDENTIFIED BY '${WP_DB_PASS}';"
      - run: 'mysql -u root -e "CREATE DATABASE ${WP_DB_NAME};"'
      - run: composer test
